FROM golang:1.16.3-alpine3.13 AS baseGo

WORKDIR /go/src/app
COPY Hello.go /go/src/app
RUN go mod init Hello/m/v2
RUN go build -o /go/src/app/hello



FROM scratch

WORKDIR /go/src/app

COPY --from=baseGo /go/src/app /go/src/app

ENTRYPOINT ["./hello" ]

